### ISSUE TITLE
Mobile Web on android

### ISSUE THREAD

**Issue by tuli** [WormBase/website-mobile#6]
Yesterday I reported the following "Same here (Samsung galaxy). I got as far as finding a hit for unc-19, but when I click on the link I just get a yellow bar. Sob."

This morning the yellow bar is now populated with my search result allowing me to view the Gene Summary. It looks pretty nice.

The Location widget shows Genetic Position and Genomic Position, the latter being a link, then there is a broken image at the bottom of the widget. It's meant to be the gbrowse image. I click on it and get "Cannot get /tools/genome/gbrowse/c_elegans_PRJNA13758?name=X:7681717..7686132.

Same error if I click on the Genomic Position link.

I then clicked on the widgets to try and open Genetics, but I got taken right back to the top page. Went back to my search via the History and see that Genetic widget has been opened. Only the Reference Allele is linked. Click on this Reference Allele and get an error (cannot get bla boa)

Click on a Strain (in the coloured display) and get Cannot get error.

Click on a Yes in the Strain table and get taken to the CGC - good. 
Click on a Strain in the Strain table and get a Cannot get error.

Overall I really like it. It's intuitive.

**Comment by antonio0** [comment]
Many thanks for the feedback and bug reports. 

The "yellow-bar only" problem happens when the API server is offline. I assume the exception that should detect this and show some error message isn't working properly.

I can confirm the bug that takes the view back to the homepage when trying to open/close widgets. @acabunoc  I believe it might have something to do with the new fastclick plugin.

I'm not able to replicate the broken links/image bug. On my phone the image takes a few second to load. @tuli It might be useful to know which browser and android version you were using, as the URLs are adapted/fixed on the client.

**Comment by tuli** [comment]
Hi @antonio0 
I've just had another look today and see the same issues as before.

The browser is the one which came with my phone - TheWorld (I'd never heard of it until I looked it up just now!).

Android version is 2.3.3 - Gingerbread

Mary Ann

**Comment by abbycabs** [comment]
I _may_ have broken things by adding FastClick. I'll take a look as soon as I get GFF3 working properly on staging (next week?)

**Comment by abbycabs** [comment]
Fixed by @sibyl229 in #12
